version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: rotctl-nginx
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - rotctl-web
    networks:
      - rotctl-network
    restart: unless-stopped

  rotctl-web:
    image: brianbruff/rotctlweb:latest
    # To build locally instead, comment out 'image' and uncomment 'build':
    # build: .
    container_name: rotctl-web
    restart: unless-stopped
    environment:
      - PORT=3000
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-Letmein!1}
      - ROTCTLD_HOST=${ROTCTLD_HOST:-192.168.100.3}
      - ROTCTLD_PORT=${ROTCTLD_PORT:-4533}
      - QTH_LATITUDE=${QTH_LATITUDE:-52.6667}
      - QTH_LONGITUDE=${QTH_LONGITUDE:--8.6333}
      - QTH_GRID_SQUARE=${QTH_GRID_SQUARE:-IO52RN}
      - QTH_LOCATION_NAME=${QTH_LOCATION_NAME:-Limerick, Ireland}
    networks:
      - rotctl-network
    # Internal port 3000 is now only accessible through nginx

networks:
  rotctl-network:
    driver: bridge
